# Travis CI file

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs
# https://github.com/svenlaater/travis-ci-ionic-yml

sudo: false
# sudo: required

### https://docs.travis-ci.com/user/languages/android/
# language: android
# jdk: oraclejdk8
# android:
#   components:
#   # - tools
#   # - platform-tools
#   - build-tools-26.0.1
#   - android-16
#   - android-26
#   licenses:
#     - 'android-sdk-preview-license-.+'
#     - 'android-sdk-license-.+'
#     - 'google-gdk-license-.+'

language: node_js
node_js:
  - "6"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1
env:
  CXX=g++-4.8
  # ANDROID_HOME=$TRAVIS_BUILD_DIR/android-sdk-linux

branches:
  only:
  - master
git:
  depth: 5

before_install:
  - npm i -g npm

  ### Unpack ssh key for git
  # - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  # - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  # - chmod 600 ~/.ssh/id_rsa
  # # Disable SSH server fingerprint verification
  # - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  ### Set up android build environment
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export ANDROID_SDK=$ANDROID_HOME
  - export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2:${PATH}
  - if [ ! -e android-sdk-linux/tools/bin/sdkmanager ];then    wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz;    tar -xvf android-sdk_r24.4-linux.tgz; fi
  # - android list sdk --extended # && android list sdk -a --extended
  - ANDROPACKS=tools,platform-tools,build-tools-26.0.1,android-16,android-26
  - if [ ! -e android-sdk-linux/tools/bin/sdkmanager ];then    ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | android update sdk -u -a -f -t ${ANDROPACKS}; fi
  ### Accept licenses:
  # - mkdir $ANDROID_HOME/licenses
  # - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  # - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  # That requests us to accept a license for the sdkmanager, and then requests us to accept new licenses not previously accepted:
  - if [ ! -e android-sdk-linux/tools/bin/sdkmanager ];then    echo y | sdkmanager --update; ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | sdkmanager --licenses; fi

install:
  - npm install -g gulp bower cordova ionic
  - npm install
  - bower update

  - chmod +x hooks/after_prepare/010_add_platform_class.js
  - if [ ! -e platforms ];then    ionic cordova prepare; else echo 'skip ionic cordova prepare'; fi   #--verbose

script:
  - ionic cordova build android #--verbose

# build cache to preserve files/folders between builds
cache: # disable cache to see 'npm install' warnings
  directories:
  - node_modules
  - platforms
  - plugins
  # - android-sdk-linux

# deploy:
#   provider: releases
#   api_key:
#     secure: YOUR_API_KEY_ENCRYPTED
#   file:
#     - "platforms/android/build/outputs/apk/android-armv7-debug.apk"
#     - "platforms/android/build/outputs/apk/android-x86-debug.apk"
#   skip_cleanup: true
#   on:
#     tags: true

# #https://github.com/floydpink/Mantis-CI/blob/master/.travis.yml:
# after_script:
#   - mkdir tempclone
#   - cd tempclone
#   - git clone $REPO.git Mantis-CI
#   - cd Mantis-CI
#   - git config user.email "imbleedingme@googlemail.com"
#   - git config user.name "Floyd Pink"
#   - cp ../../bin/MantisCI-release.apk deploy/ -f
#   - git add .
#   - git commit -a -m "Committed from CI (build number - $((TRAVIS_JOB_ID - 1))) [ci skip]"
#   - git push origin master
# env:
#   global:
#     # Repo read-write address
#     - REPO="git@github.com:floydpink/Mantis-CI"
#     # SSH key. Encoded. See https://gist.github.com/4631240
#     - secure: "Cq2JLLOoLRUqz7YETnSk2pysaIVxbuxuS+hamqmPN24ImHf4myrWm3THq37s\n1TWn4UBDKPRxZPdllzMTeFSSHxXCKUW4sQBhGogkv1Qf2TY2iliv08rf+pXc\nL7xgqkQE4eYizqsWi9+yWo3NHi6gYLe7nIufEaJtIe08kOmoLcI="
#     - secure: "I2pEXbp+k3Kgi1p8wQhsmqHTUn+mC54Ey/aDHXYTb4+sarDwifsSE45l/gca\nwlbRjU6vU4TO/paxgbFfDDok5E28pu7vuMxS+ooSaQiWCwC6wtBS03gG+KnY\n5fid8AouVCLs8GC4HMhGG8xK70mgSnrG6/z8K0nEDmV3vQpWPVI="
