# Travis CI file

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs

sudo: false

### https://docs.travis-ci.com/user/languages/android/
# language: android
# jdk: oraclejdk8
# android:
#   components:
#   # - tools
#   # - platform-tools
#   - build-tools-26.0.1
#   - android-16
#   - android-26
#   licenses:
#     - 'android-sdk-preview-license-.+'
#     - 'android-sdk-license-.+'
#     - 'google-gdk-license-.+'

language: node_js
node_js: "6"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1
env:
  CXX=g++-4.8
  # ANDROID_HOME=$TRAVIS_BUILD_DIR/android-sdk-linux

branches:
  only:
  - master
git:
  depth: 5

before_install:
  - npm i -g npm

  ### Unpack ssh key for git
  # - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  # - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  # - chmod 600 ~/.ssh/id_rsa
  # # Disable SSH server fingerprint verification
  # - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  ### Set up android build environment
  - source ./scripts/android_sdk_install.sh

install:
  - npm install -g gulp bower cordova ionic
  - npm install
  - bower update
  - source ./scripts/ionic_cordova_prepare.sh

# before_script:
#   - npm config get prefix
#   - set | grep -P "^\w+="
#   - set | grep -P "^\w+=.*/home/travis"

script:
  - echo 'script run...'; echo -en 'travis_fold:start:script.1\\r'; SECONDS=0

  -   ionic cordova build android # --verbose

  # -   ionic cordova build android &

  ### Release build:
  # #     # keystore    CN=Your name, OU=OrgUnit, O=Org, L=city/Locality, S=STate/province, C=Country code
  # -     keystoreFile=ikarus512-trackSave.keystore; keystoreAlias=ikarus512trackSave; storePassword=1211243; keyPassword=123ljNjl; keystoreValidity=10000 # days
  # -     keytool -genkey -v -noprompt -alias $keystoreAlias -keystore $keystoreFile -storepass $storePassword -keypass $keyPassword -keyalg RSA -keysize 2048 -validity $keystoreValidity -dname "CN=ikarus512, OU=ikarus512, O=HSH, L=NN, S=RU, C=RU"
  # # -   ionic cordova plugin rm cordova-plugin-console
  # # -   ionic cordova build android --release -- --keystore=$keystoreFile --alias=$keystoreAlias --storePassword=$storePassword --password=$keyPassword
  # # -   ionic cordova build android --release
  # # -   jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $keystoreFile android-armv7-release-unsigned.apk $keystoreAlias
  # # -   jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $keystoreFile android-x86-release-unsigned.apk $keystoreAlias
  # - pushd platforms/android/build/outputs/apk
  # -   jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ../../../../../$keystoreFile android-armv7-release-unsigned.apk $keystoreAlias -storepass $storePassword -keypass $keyPassword
  # -   jarsigner -verify android-armv7-release-unsigned.apk $keystoreAlias
  # #   C:\Apps\AndroidSDK\build-tools\25.0.2\zipalign
  # #   /c/Apps/AndroidSDK/build-tools/25.0.2/zipalign -v 4 android-armv7-release-unsigned.apk trackSave-armv7.apk
  # - popd

  - duration=$SECONDS; echo -en 'travis_fold:end:script.1\\r'
  - echo "script run $(($duration / 60))m $(($duration % 60))s"
  - ls platforms/android/build/outputs/apk

# build cache to preserve files/folders between builds
cache: # disable cache to see 'npm install' warnings
  directories:
  - node_modules
  - platforms
  - plugins
  - android-sdk-linux
  - $NVM_DIR # $(npm config get prefix)

# deploy:
#   provider: releases
#   api_key:
#     secure: YOUR_API_KEY_ENCRYPTED
#   file:
#     - "platforms/android/build/outputs/apk/android-armv7-debug.apk"
#     - "platforms/android/build/outputs/apk/android-x86-debug.apk"
#   skip_cleanup: true
#   on:
#     tags: true

# #https://github.com/floydpink/Mantis-CI/blob/master/.travis.yml:
# after_script:
#   - mkdir tempclone
#   - cd tempclone
#   - git clone $REPO.git Mantis-CI
#   - cd Mantis-CI
#   - git config user.email "imbleedingme@googlemail.com"
#   - git config user.name "Floyd Pink"
#   - cp ../../bin/MantisCI-release.apk deploy/ -f
#   - git add .
#   - git commit -a -m "Committed from CI (build number - $((TRAVIS_JOB_ID - 1))) [ci skip]"
#   - git push origin master
# env:
#   global:
#     # Repo read-write address
#     - REPO="git@github.com:floydpink/Mantis-CI"
#     # SSH key. Encoded. See https://gist.github.com/4631240
#     - secure: "Cq2JLLOoLRUqz7YETnSk2pysaIVxbuxuS+hamqmPN24ImHf4myrWm3THq37s\n1TWn4UBDKPRxZPdllzMTeFSSHxXCKUW4sQBhGogkv1Qf2TY2iliv08rf+pXc\nL7xgqkQE4eYizqsWi9+yWo3NHi6gYLe7nIufEaJtIe08kOmoLcI="
#     - secure: "I2pEXbp+k3Kgi1p8wQhsmqHTUn+mC54Ey/aDHXYTb4+sarDwifsSE45l/gca\nwlbRjU6vU4TO/paxgbFfDDok5E28pu7vuMxS+ooSaQiWCwC6wtBS03gG+KnY\n5fid8AouVCLs8GC4HMhGG8xK70mgSnrG6/z8K0nEDmV3vQpWPVI="
