# Travis CI file

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js
node_js: "6"
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1

env:
  global:
    - CXX=g++-4.8
    - ANDROID_HOME=$TRAVIS_BUILD_DIR/android-sdk-linux
    - zipalign=$ANDROID_HOME/build-tools/26.0.1/zipalign
  matrix:
    - JOBNAME=tripSave_debug   BUILD_SCRIPT=scripts/ionic_cordova_build_android_debug.sh
    - JOBNAME=tripSave_release BUILD_SCRIPT=scripts/ionic_cordova_build_android_release.sh

branches:
  only:
    - master
  except: # tags starting with vX.X.X (usually commited by travis)
    - /^v?\d+\.\d+\.\d+/

git:
  depth: 100

cache:
  timeout: 300 # 5*60 seconds
  directories:
  - node_modules
  - platforms
  - plugins
  - android-sdk-linux
  - $NVM_DIR # $(npm config get prefix)

before_install:
  - npm i -g npm
  - npm --version
  - source ./scripts/android_sdk_install.sh

install:
  - npm install -g gulp bower cordova ionic
  - npm install
  - bower update
  - source ./scripts/ionic_cordova_prepare.sh

before_script:
  - $BUILD_SCRIPT
  - scripts/deploy_github_releases.sh $JOBNAME

script:
  - ls platforms/android/build/outputs/apk
  - ls releases
  - echo 1
